# Generated by Django 3.1.3 on 2024-06-28 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicamentos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicamento',
            old_name='como_usar',
            new_name='enfermedad',
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
